Summary: Cleaning up a little Thyra code and enabling checked STL
Somehow the CMake build of several files was broken after my last checkin.


Specific changes:
-----------------

(*) PackageArchSetupStrongCompileWarnings.cmake: Added
-D_GLIBCXX_DEBUG when doing a debug build.

(*) Teuchos_ConfigDefs.hpp: Removed _GLIBCXX_DEBUG define because it
really has to be defined on the command-line because of pacakges like
ML that use the STL before they include Teuchos_ConfigDefs.hpp and
everything falls apart.

(*) Teuchos_PtrDecl.hpp,
teuchos/test/MemoryManagement/Ptr_UnitTests.cpp: Added support and
unit tests for other use cases for rcpFromPtr(...).

(*) Phalanx_DataContainer[_Def].hpp: Fixed a compile problem when
compiling with -D_GLIBCXX_DEBUG

(*) packages/fei/*: I fixed several lines of code where the braket
operator was being used illegally on an unsized vectors exposed by
-D_GLIBCXX_DEBUG.  Lots of tests are still failing with with
-D_GLIBCXX_DEBUG but everything passes fine in MPI mode with this
turned off.  Alan is going to fix these as soon as I check in.

(*) packages/thyra/*: Cleaning up some code but nothing major.

-D_GLIBCXX_DEBUG(*) packages/thyra/test/definition: Removed --verbose from
sillyCgSolve tests.

(*) sampleScripts/linux-godel-gcc-4.1.2-serial-debug-cmake: Removing
-DTrilinos_ENABLE_Anasazi:BOOL=OFF because Anasazi builds in debug
mode again.


Tested on godel.sandia.gov with:
--------------------------------

(*) CMake serial debug rebuild (all but 9 of the 415 tests ran passed,
see below)

(*) CMake mpi release rebuild (all but one of the 391 tests ran
passed, see below)

(*) Autotools serial debug library and thyra tests rebuild (all 33
thyra tests ran passed)


Failing tests:
--------------


(*) CMake serial debug

The following tests FAILED:
         19 - Teuchos_Containers_test (SEGFAULT)
        220 - Stratimikos_test_single_belos_thyra_solver_driver_1 (OTHER_FAULT)
        223 - Stratimikos_test_single_belos_thyra_solver_driver_4 (OTHER_FAULT)
        224 - Stratimikos_test_single_belos_thyra_solver_driver_5 (OTHER_FAULT)
        249 - FEI_fei_test (OTHER_FAULT)
        254 - FEI_lagrange_20quad_AZ (OTHER_FAULT)
        256 - FEI_multifield_slave (OTHER_FAULT)
        257 - FEI_slave_20quad (OTHER_FAULT)
        258 - FEI_slave_20quad_old (OTHER_FAULT)

The failures with the tests Stratimikos_test_single_belos_thyra_solve*
appear to be in Ifpack according to valgrind.  Here is what the first
error looks like:

==1344==
==1344== 8 bytes in 1 blocks are still reachable in loss record 1 of 128
==1344==    at 0x4A06CB9: operator new[](unsigned long) (vg_replace_malloc.c:199)
==1344==    by 0xDA9FFE: Epetra_MultiVector::AllocateForCopy() (Epetra_MultiVector.cpp:244)
==1344==    by 0xDAC522: Epetra_MultiVector::Epetra_MultiVector(Epetra_BlockMap const&, int, bool) (Epetra_MultiVector.cpp:61)
==1344==    by 0xDD35C6: Epetra_Vector::Epetra_Vector(Epetra_BlockMap const&, bool) (Epetra_Vector.cpp:35)
==1344==    by 0xA0881E: Ifpack_LocalFilter::Ifpack_LocalFilter(Teuchos::RCP<Epetra_RowMatrix const> const&) (Ifpack_LocalFilter.cpp:67)
==1344==    by 0x9D186F: Ifpack_AdditiveSchwarz<Ifpack_ILUT>::Setup() (Ifpack_AdditiveSchwarz.h:449)
==1344==    by 0x9D27A6: Ifpack_AdditiveSchwarz<Ifpack_ILUT>::Initialize() (Ifpack_AdditiveSchwarz.h:587)
==1344==    by 0x9593C3: Thyra::IfpackPreconditionerFactory::initializePrec(Teuchos::RCP<Thyra::LinearOpSourceBase<double, double> const> const&, Thyra::PreconditionerBase<double, double>*,\
 Thyra::ESupportSolveUse) const (Thyra_IfpackPreconditionerFactory.cpp:224)
==1344==    by 0x920BCC: Thyra::BelosLinearOpWithSolveFactory<double>::initializeOpImpl(Teuchos::RCP<Thyra::LinearOpSourceBase<double, double> const> const&, Teuchos::RCP<Thyra::LinearOpSou\
rceBase<double, double> const> const&, Teuchos::RCP<Thyra::PreconditionerBase<double, double> const> const&, bool, Thyra::LinearOpWithSolveBase<double, double>*, Thyra::ESupportSolveUse) co\
nst (Thyra_BelosLinearOpWithSolveFactory.hpp:410)
==1344==    by 0x922951: Thyra::BelosLinearOpWithSolveFactory<double>::initializeOp(Teuchos::RCP<Thyra::LinearOpSourceBase<double, double> const> const&, Thyra::LinearOpWithSolveBase<double\
, double>*, Thyra::ESupportSolveUse) const (Thyra_BelosLinearOpWithSolveFactory.hpp:124)
==1344==    by 0x8C36F9: void Thyra::initializeOp<double>(Thyra::LinearOpWithSolveFactoryBase<double, double> const&, Teuchos::RCP<Thyra::LinearOpBase<double, double> const> const&, Thyra::\
LinearOpWithSolveBase<double, double>*, Thyra::ESupportSolveUse) (Thyra_LinearOpWithSolveFactoryHelpers.hpp:86)
==1344==    by 0x800BBE: Thyra::test_single_belos_thyra_solver(std::string, bool, bool, int, int, double, double, double, bool, bool, Teuchos::ParameterList*, Teuchos::ParameterList*, Teuch\
os::basic_FancyOStream<char, std::char_traits<char> >*) (test_single_belos_thyra_solver.cpp:122)
==1344==    by 0x7F52B2: main (test_single_belos_thyra_solver_driver.cpp:96)

The failures in the FEI are due to easier STL violations.  For
example, the first FEI failure is:



$ ctest -W 100 -R FEI_fei_test -VV
UpdateCTestConfiguration  from :/home/rabartl/PROJECTS/Trilinos.base/BUILDS/CMAKE/GCC-4.1.2/SERIAL_DEBUG/DartConfiguration.tcl
Parse Config file:/home/rabartl/PROJECTS/Trilinos.base/BUILDS/CMAKE/GCC-4.1.2/SERIAL_DEBUG/DartConfiguration.tcl
 Add coverage exclude regular expressions.
Start processing tests
UpdateCTestConfiguration  from :/home/rabartl/PROJECTS/Trilinos.base/BUILDS/CMAKE/GCC-4.1.2/SERIAL_DEBUG/DartConfiguration.tcl
Parse Config file:/home/rabartl/PROJECTS/Trilinos.base/BUILDS/CMAKE/GCC-4.1.2/SERIAL_DEBUG/DartConfiguration.tcl
Test project /home/rabartl/PROJECTS/Trilinos.base/BUILDS/CMAKE/GCC-4.1.2/SERIAL_DEBUG
Constructing a list of tests
Done constructing a list of tests
Changing directory into /home/rabartl/PROJECTS/Trilinos.base/BUILDS/CMAKE/GCC-4.1.2/SERIAL_DEBUG/packages/fei/test
249/415 Testing FEI_fei_test .......................................................................................
Test command: /home/rabartl/PROJECTS/Trilinos.base/BUILDS/CMAKE/GCC-4.1.2/SERIAL_DEBUG/packages/fei/test/FEI_fei_test.exe -d . -test unit_tests
Test timeout computed to be: 600
FEI version: 2.24.0
testing feiArray.[append,dataPtr]...ok
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/debug/vector:192:
    error: attempt to subscript container with out-of-bounds index 0, but
    container only holds 0 elements.

Objects involved in the operation:
sequence testing fei::FieldMask..."this" @ 0x0x7fff50207110 {
  type = N15__gnu_debug_def6vectorIiSaIiEEE;
}
-- Process completed

*** Exception executing: Child aborted
***Exception: Other

0% tests passed, 1 tests failed out of 1

The following tests FAILED:
        249 - FEI_fei_test (OTHER_FAULT)
Errors while running CTest





(*) CMake mpi release

The following tests FAILED:
        129 - Tpetra_CrsMatrix_UnitTests_MPI_4 (Failed)

This test is still failing.  Here is the error message:


92. CrsMatrix_int_ComplexFloat_FullMatrixTriDiag_UnitTest ...
 A.getNumGlobalNonzeros() = 10 == 3*numImages-2 = 10 : passed
 A.getNumMyNonzeros() = 2 == myNNZ = 2 : passed
 A.getNumGlobalRows() = 4 == numImages = 4 : passed
 A.getNumMyRows() = 1 == 1 : passed
 A.getNumMyCols() = 2 == myNNZ = 2 : passed
 A.getNumGlobalDiagonals() = 4 == numImages = 4 : passed
 A.getNumMyDiagonals() = 1 == 1 : passed
 A.getGlobalMaxNumEntries() = 3 == 3 = 3 : passed
 A.getMyMaxNumEntries() = 2 == myNNZ = 2 : passed
 A.getIndexBase() = 0 == 0 : passed
 A.getRowMap().isSameAs(A.getColMap()) = false == false : passed
 A.getRowMap().isSameAs(A.getDomainMap()) = true == true : passed
 A.getRowMap().isSameAs(A.getRangeMap()) = true == true : passed
 Comparing norms == zeros ...
 Error, relErr(norms[0],zeros[0]) = relErr(4.51874e-15,0) = 3.79059e-08 <= tol = 0: failed!

 Error, relErr(norms[1],zeros[1]) = relErr(6.39046e-15,0) = 5.36071e-08 <= tol = 0: failed!

 Error, relErr(norms[2],zeros[2]) = relErr(6.39046e-15,0) = 5.36071e-08 <= tol = 0: failed!

 Error, relErr(norms[3],zeros[3]) = relErr(4.51874e-15,0) = 3.79059e-08 <= tol = 0: failed!
 [FAILED]
 Location: /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/tpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp:716


97. CrsMatrix_int_ComplexFloat_TheEyeOfTruthDistAlloc_UnitTest ...
 eye.getNumGlobalNonzeros() = 40 == numImages*numLocal = 40 : passed
 eye.getNumMyNonzeros() = 10 == numLocal = 10 : passed
 eye.getNumGlobalRows() = 40 == numImages*numLocal = 40 : passed
 eye.getNumMyRows() = 10 == numLocal = 10 : passed
 eye.getNumMyCols() = 10 == numLocal = 10 : passed
 eye.getNumGlobalDiagonals() = 40 == numImages*numLocal = 40 : passed
 eye.getNumMyDiagonals() = 10 == numLocal = 10 : passed
 eye.getGlobalMaxNumEntries() = 1 == 1 = 1 : passed
 eye.getMyMaxNumEntries() = 1 == 1 = 1 : passed
 eye.getIndexBase() = 0 == 0 = 0 : passed
 eye.getRowMap().isSameAs(eye.getColMap()) = true == true : passed
 eye.getRowMap().isSameAs(eye.getDomainMap()) = true == true : passed
 eye.getRowMap().isSameAs(eye.getRangeMap()) = true == true : passed
 Comparing norms == zeros ...
 Error, relErr(norms[0],zeros[0]) = relErr(1.06483e-06,0) = 0.89932 <= tol = 0: failed!

 Error, relErr(norms[1],zeros[1]) = relErr(1.19552e-06,0) = 0.909328 <= tol = 0: failed!

 Error, relErr(norms[2],zeros[2]) = relErr(9.50519e-07,0) = 0.888561 <= tol = 0: failed!

 Error, relErr(norms[3],zeros[3]) = relErr(1.05803e-06,0) = 0.898739 <= tol = 0: failed!

 Error, relErr(norms[4],zeros[4]) = relErr(1.12657e-06,0) = 0.904309 <= tol = 0: failed!
 [FAILED]
 Location: /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/tpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp:581