Using namespace std; if std::min is used, Drekar build fails on Red Sky:
/ascldap/users/phtsuji/Drekar_code/Trilinos/packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_PYR_C1_FEMDef.hpp(202): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (panzer::Traits::FadType, Sacado::ELRCacheFad::Expr<Sacado::ELRCacheFad::SubtractionOp<Sacado::ELRCacheFad::ConstExpr<double>, Sacado::ELRCacheFad::Expr<Sacado::ELRCacheFad::GeneralFad<double, Sacado::Fad::DynamicStorage<double, double>>>>>)
          z = std::min(z, 1-eps);
              ^