SUMMARY:  Got HDF5 wrappers to build in epetraext
BUGS:     None filed

CHECKLIST:

1) Did you add any source files? Noe

2) Did you update or change the build system? No

3) Did you rerun the test suite on at least the packages that you
   changed? Yes, but just epetraext and just in a serial build

COMMENTS:

Here I just added a bunch of missing std:: namespace qualifications after the
remove of 'using namespace std' as per the previous refactoring.

Here are the files that I changed:

  M example/inout/HDF5_IO.cpp
  M src/inout/EpetraExt_DistArray.h
  M src/inout/EpetraExt_HDF5.cpp
  M src/inout/EpetraExt_HDF5_DistObject.cpp
  M src/inout/EpetraExt_HDF5_Handle.h

I build this in a serial build successfully.  However, there are no tests in
the test suite to check this, at least not in epetraext.  There are some
examples that build and I ran these manually but I don't know if they worked
or not (they just did not segfault).

I tried this in an MPI build and I got the following link error:

  /usr/local/mpi/bin/mpiCC -DHAVE_CONFIG_H -I. -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src  -I/home/rabartl/PROJECTS/Trilinos.base/BUILDS/GCC-3.4.6/MPI_DEBUG/packages/epetraext/src -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/block -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/btf -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/coloring -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/distdir -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/inout -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/matlab -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/model_evaluator -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/transform -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/zoltan -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetra/src -I/home/rabartl/PROJECTS/Trilinos.base/BUILDS/GCC-3.4.6/MPI_DEBUG/packages/epetra/src -I/home/rabartl/PROJECTS/Trilinos.base/BUILDS/GCC-3.4.6/MPI_DEBUG/packages/teuchos/src -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/teuchos/src -I/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/triutils/src -I/home/rabartl/PROJECTS/Trilinos.base/BUILDS/GCC-3.4.6/MPI_DEBUG/packages/triutils/src -I/usr/local/hdf5/include -I/usr/local/sz/include   -g -ansi -Wall -MT EpetraExt_BlockUtility.o -MD -MP -MF .deps/EpetraExt_BlockUtility.Tpo -c -o EpetraExt_BlockUtility.o `test -f '/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/block/EpetraExt_BlockUtility.cpp' || echo '/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/'`/home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/block/EpetraExt_BlockUtility.cpp
  /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp: In member function `void EpetraExt::HDF5::Read(const std::string&, Epetra_MultiVector*&)':
  /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:999: error: `H5Pset_dxpl_mpio' was not declared in this scope
  /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:999: warning: unused variable 'H5Pset_dxpl_mpio'
  /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp: In member function `void EpetraExt::HDF5::Read(const std::string&, const std::string&, std::string&)':
  /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1392: warning: unused variable 'typesize_id'
  /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp: In member function `void EpetraExt::HDF5::Write(const std::string&, const std::string&, int, int, int, const void*)':
  /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1504: error: `H5Pset_dxpl_mpio' was not declared in this scope
  /home/rabartl/PROJECTS/Trilinos.base/Trilinos/packages/epetraext/src/inout/EpetraExt_HDF5.cpp:1504: warning: unused variable 'H5Pset_dxpl_mpio'
  make[2]: *** [EpetraExt_HDF5.o] Error 1

I greped the nm from the hdf5 libraries and I could not find the symbol
'H5Pset_dxpl_mpio'.  However, I also noticed from:

  $ pwd
  /home/rabartl/PROJECTS/Trilinos.base/Trilinos/commonTools/test/harness/invoke-configures
  [rabartl@gabriel invoke-configures]$ grep -nH 'hdf5' *
  darwin-s858352:8:--with-libs="-lsuperlu -lumfpack -lamd -lg2c -lexpat -lhdf5" \
  darwin-s858352:22:--enable-epetraext-hdf5 \

that the hdf5 wrappers are not be tested with MPI on any of the test platforms
so I am not going to worry about this.