Tpetra: Fixed Bug 5399 test so it won't have link errors on CUDA.
perseus.sandia.gov does a CUDA build with the Kokkos refactor version
of Tpetra.  It caught the following link error:

CMakeFiles/cuda_compile.dir/./cuda_compile_generated_Map_Bug5399_CU.cu.o:(.bss+0x10): multiple definition of `instance_Map_Bug5399_UnitTest'
CMakeFiles/Tpetra_Map_Bug5399.dir/Map_Bug5399.cpp.o:(.bss+0x0): first defined here
CMakeFiles/cuda_compile.dir/./cuda_compile_generated_Map_Bug5399_CU.cu.o: In function `Map_Bug5399_UnitTest::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
tmpxft_000034d5_00000000-3_Map_Bug5399_CU.cudafe1.cpp:(.text+0x4c0): multiple definition of `Map_Bug5399_UnitTest::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const'
CMakeFiles/Tpetra_Map_Bug5399.dir/Map_Bug5399.cpp.o:Map_Bug5399.cpp:(.text+0x9f0): first defined here
collect2: ld returned 1 exit status

This indicates that I forgot to put the macros in the test's .cpp file
that ensure CUDA only builds the .cu file, not the .cpp file, in order
to avoid conflicting multiple definitions of the unit test.  This
commit fixes that.

Build/Test Cases Summary
Enabled Packages: Tpetra, KokkosCore, KokkosCompat, KokkosMpiComm, KokkosContainers, KokkosLinAlg
0) MPI_DEBUG => Test case MPI_DEBUG was not run! => Does not affect push readiness! (-1.00 min)
1) SERIAL_RELEASE => Test case SERIAL_RELEASE was not run! => Does not affect push readiness! (-1.00 min)
2) MPI_RELEASE_KOKKOS_REFACTOR => passed: passed=77,notpassed=0 (1.40 min)
3) SERIAL_RELEASE_KOKKOS_REFACTOR => passed: passed=58,notpassed=0 (0.09 min)