SUMMARY: Getting Sacado to compile with g++ -ansi
BUGS: 3922

CHECKLIST:

1) Did you add any source or other files needed for building, testing,
   or documentation? No

2) Did you update or change the build system (other than just adding
   source files)? No

3) Did you do a cvs update *very* recently before rebuilding and
   retesting? Yes

4) If justified, did you type 'make partial-clean' and then rebuild all
   libraries and executables with 'make everything'? Yes, but only serial
   debug

5) Did you rerun the test suite on at least the packages that you
   changed (rerunning the entire Trlinos test suite on all affected
   packages is *strongly* recommended)? Yes, all but 1 of the
   877 test run passed (see below).

COMMENTS:

Here was an email I sent out describing the problem:



=======================================================================

This build failure looks like this is an error with Rad in Sacado.  The build error can be seen at:

    http://gabriel.sandia.gov/charon-tests/2008-06-03-00-00/2D_64BITgnu3_hessian_opt_tridev/build-charon.out

which shows:

---------------------------------------------------------------------

/mnt/disk2/rabartl/Charon.nightly-tests-4/TrilinosDev/Updated/Charon_TPL/trilinos/development/include/64BITgnu3_opt/Sacado_trad.hpp: In instantiation of `Sacado::Rad::ADcontext<FadType>::<anonymous union>':
/mnt/disk2/rabartl/Charon.nightly-tests-4/TrilinosDev/Updated/Charon_TPL/trilinos/development/include/64BITgnu3_opt/Sacado_trad.hpp:222:   instantiated from `Sacado::Rad::ADcontext<FadType>'
/mnt/disk2/rabartl/Charon.nightly-tests-4/TrilinosDev/Updated/Charon_TPL/trilinos/development/include/64BITgnu3_opt/Sacado_trad.hpp:1321:   instantiated from `Sacado::Rad::ADvari<FadType>'
/mnt/disk2/rabartl/Charon.nightly-tests-4/TrilinosDev/Updated/Charon_proj/Charon_src/charon/function/reactingflow/Charon_MomentumSource_GravityT.h:139:   instantiated from `void charon::rf::GravityMomentumSource<ScalarT>::evaluateProvidedVariables(charon::VariableManager&, int, std::vector<int, std::allocator<int> >&, charon::CharonElement*, double*, double*, double**, Vector**, bool) [with ScalarT = RadFadType]'
/mnt/disk2/rabartl/Charon.nightly-tests-4/TrilinosDev/Updated/Charon_proj/Charon_src/charon/function/reactingflow/Charon_MomentumSource_Gravity.C:23:   instantiated from here
/mnt/disk2/rabartl/Charon.nightly-tests-4/TrilinosDev/Updated/Charon_TPL/trilinos/development/include/64BITgnu3_opt/Sacado_trad.hpp:221: error: member `Sacado::Rad::ADmemblock<FadType> Sacado::Rad::ADcontext<FadType>::<anonymous union>::First0' with constructor not allowed in union
/mnt/disk2/rabartl/Charon.nightly-tests-4/TrilinosDev/Updated/Charon_TPL/trilinos/development/include/64BITgnu3_opt/Sacado_trad.hpp:221: error: member `Sacado::Rad::ADmemblock<FadType> Sacado::Rad::ADcontext<FadType>::<anonymous union>::First0' with destructor not allowed in union
/mnt/disk2/rabartl/Charon.nightly-tests-4/TrilinosDev/Updated/Charon_TPL/trilinos/development/include/64BITgnu3_opt/Sacado_trad.hpp:221: error: member `Sacado::Rad::ADmemblock<FadType> Sacado::Rad::ADcontext<FadType>::<anonymous union>::First0' with copy assignment operator not allowed in union
make: *** [function/reactingflow/Charon_MomentumSource_Gravity.o] Error 1

---------------------------------------------------------------------

Note that the Sacado examples failed to compile also last night with a similar error as shown at:

    http://software.sandia.gov/trilinos/developer/test_harness/results/make_output.html?mid=60&bid=62&cid=2

Wwhich shows:

---------------------------------------------------------------------

/mnt/disk2/rabartl/Trilinos.nightly-tests/Trilinos/packages/sacado/src/Sacado_trad.hpp: In instantiation of `Sacado::Rad::ADcontext<Sacado::Fad::DFad<double, double> >::<anonymous union>':
/mnt/disk2/rabartl/Trilinos.nightly-tests/Trilinos/packages/sacado/src/Sacado_trad.hpp:222:   instantiated from `Sacado::Rad::ADcontext<Sacado::Fad::DFad<double, double> >'
/mnt/disk2/rabartl/Trilinos.nightly-tests/Trilinos/packages/sacado/src/Sacado_trad.hpp:1321:   instantiated from `Sacado::Rad::ADvari<Sacado::Fad::DFad<double, double> >'
../../../../packages/sacado/example/trad_dfad_example.cpp:83:   instantiated from here
/mnt/disk2/rabartl/Trilinos.nightly-tests/Trilinos/packages/sacado/src/Sacado_trad.hpp:221: error: member `Sacado::Rad::ADmemblock<Sacado::Fad::DFad<double, double> > Sacado::Rad::ADcontext<Sacado::Fad::DFad<double, double> >::<anonymous union>::First0' with constructor not allowed in union
/mnt/disk2/rabartl/Trilinos.nightly-tests/Trilinos/packages/sacado/src/Sacado_trad.hpp:221: error: member `Sacado::Rad::ADmemblock<Sacado::Fad::DFad<double, double> > Sacado::Rad::ADcontext<Sacado::Fad::DFad<double, double> >::<anonymous union>::First0' with destructor not allowed in union
/mnt/disk2/rabartl/Trilinos.nightly-tests/Trilinos/packages/sacado/src/Sacado_trad.hpp:221: error: member `Sacado::Rad::ADmemblock<Sacado::Fad::DFad<double, double> > Sacado::Rad::ADcontext<Sacado::Fad::DFad<double, double> >::<anonymous union>::First0' with copy assignment operator not allowed in union mv -f .deps/dmfad_example-dmfad_example.Tpo .deps/dmfad_example-dmfad_example.Po

---------------------------------------------------------------------



=======================================================================


Here was the change I made:

    Index: src/Sacado_trad.hpp
    ===================================================================
    RCS file: /space/CVS/Trilinos/packages/sacado/src/Sacado_trad.hpp,v
    retrieving revision 1.22
    diff -r1.22 Sacado_trad.hpp
    219c219
    <       union {
    ---
    >   struct {


There is a single failing test:

    sacado - trad_dfad_example.exe...                      ! FAILED     <1 second

I suspect that I broke this with this change but it is far better to get
Sacado tests and examples and Charon + Trilinos Dev to build and all but one
run than to get not test results at all.