Thyra: Addressed build errors mentioned on trilinos-users.
Rossi Simone wrote the trilinos-users list and observed the following:

I'm compiling Trilinos 11.6.1 on OS X 10.9.2 with the latest version
of xcode, which comes with clang 503.0.38.  In particular when
compiling Rythmos, I get the following compilation error:

.../packages/thyra/core/src/support/operator_vector/adapter_support/Thyra_DefaultSpmdVectorSpace_def.hpp:89:17: error:
    cannot refer to class template 'rank' without a template argument list
        procRank_ = rank(*comm);
                    ^

I had the same issue in older version of Trilinos 11.
I temporarily solved the compilation error by using

procRank_ = Teuchos::rank(*comm);

in Thyra_DefaultSpmdVectorSpace_def.hpp.

I took a look at Thyra and noticed the same compilation error:
Teuchos::rank was not imported into the into the Thyra namespace, and
was getting used without a namespace qualifier.  I looked at this and
other Thyra file in the same directory, and noticed a few other
potential errors like this.  This commit fixes those errors.

We need to port this fix to the (new) 11.8 branch of Trilinos.

Build/Test Cases Summary
Enabled Packages: ThyraCore
Enabled all Forward Packages
0) MPI_DEBUG => passed: passed=296,notpassed=0 (11.40 min)
1) SERIAL_RELEASE => Test case SERIAL_RELEASE was not run! => Does not affect push readiness! (-1.00 min)