ROL: Fixed incorrect use of nonconst reference for Teuchos::RCP
When passing Teuchos::RCP, std::shared_ptr, or anything like that
into a function or method as an input argument, please pass it as
a const reference ("const Teuchos::RCP<T>&"), not as a nonconst
reference.  Passing by nonconst reference causes build errors if
you attempt to assign to the reference a default argument (such
as Teuchos::null).  The build errors look like this (Clang 3.7):

.../Trilinos/packages/rol/src/algorithm/ROL_OptimizationProblem.hpp:124:64: error: non-const lvalue reference to type
      'Teuchos::RCP<Teuchos::ParameterList>' cannot bind to a temporary of type 'Teuchos::ENull'
                      Teuchos::RCP<Teuchos::ParameterList>    &parlist = Teuchos::null)
                                                               ^         ~~~~~~~~~~~~~
.../Trilinos/packages/rol/src/algorithm/ROL_OptimizationProblem.hpp:124:64: note: passing argument to parameter 'parlist' here
.../Trilinos/packages/rol/src/algorithm/ROL_OptimizationProblem.hpp:133:64: error: non-const lvalue reference to type
      'Teuchos::RCP<Teuchos::ParameterList>' cannot bind to a temporary of type 'Teuchos::ENull'
                      Teuchos::RCP<Teuchos::ParameterList>    &parlist = Teuchos::null)

Furthermore, even if it compiles, passing by nonconst reference
does not express the correct intent.  For example:

// 'ptr' is an OUTPUT argument.  Callers see the new pointer.
void foo (std::shared_ptr<Foo>& ptr) {
  ptr = std::shared_ptr<Foo> (new Foo ());
}

// 'ptr' is an INPUT argument.  Callers do NOT see any changes
// to the pointer.  However, callers may see changes to the Foo
// object, since it's a nonconst pointer.
void foo (const std::shared_ptr<Foo>& ptr) {
  ptr->modify ();
}

If this is confusing, consider the difference between "Foo* const"
and "const Foo*".  The former means you can't change the pointer
(the address -- just a 64-bit unsigned integer), but you can call
nonconst methods on the Foo object.  The latter means you _can_
change the pointer, but you canNOT call nonconst methods on the
Foo object.

If you still find this confusing, just pass std::shared_ptr,
Teuchos::RCP, and the like by value.

Build/Test Cases Summary
Enabled Packages: ROL
Disabled Packages: FEI,STK,PyTrilinos,Intrepid2
0) MPI_DEBUG => Test case MPI_DEBUG was not run! => Does not affect push readiness! (-1.00 min)
1) SERIAL_RELEASE => Test case SERIAL_RELEASE was not run! => Does not affect push readiness! (-1.00 min)
2) MPI_DEBUG_COMPLEX => passed: passed=53,notpassed=0 (3.45 min)
3) SERIAL_RELEASE => passed: passed=66,notpassed=0 (5.35 min)