Summary: More explicit instantiation for Thyra and some other experimention
A) Changes to Teuchos:
----------------------

(*) teuchos/src/CMakeLists.txt, teuchos/src/Makefile.am,
Teuchos_ExpandScalarTypeMacros.hpp: Added a new file that contains macros for
expanding arbitrary code based on a template argument.  I am using this in
Thyra to support creating inline non-templated functions to call templated
function.  This is to allow C++ compiler to perform implicit conversions in
input arguments.


B) Changes to Thyra:
--------------------

(*) thyra/example/operator_vector/sillyCgSolve.hpp: Removed one explicit
template argument from a non-member call allowed

M packages/thyra/refactoring/explicit-instant.200902.token-list

(*) thyra/src/Makefile.am: Addition of new explicit instantiation files

(*) Thyra_LinearOpBaseDecl.hpp: Added first example of inline non-template
non-member functions calling template functions to allow for implicit type
conversion.  This is an experiment to see if this can make non-member
functions with Thyra easier to use.

(*) Thyra_LinearOpWithSolveTester.hpp: Added a missing header hidden from
moving to explicit instantiation.

(*) Thyra_DefaultSpmdVectorSpace_def.hpp,
Thyra_DefaultProductVectorSpace_decl.hpp,
Thyra_DefaultProductVectorSpace_def.hpp, Thyra_VectorDefaultBase*pp: Removing
some shadowing warnings.

(*) Thyra_DefaultMultipliedLinearOp*pp, Thyra_DefaultProductMultiVector*pp,
Thyra_DefaultProductVector*pp, Thyra_DefaultScaledAdjointLinearOp*pp,
Thyra_LinearOpTester*pp: Moved to explicit instantiation and deprecating use
of raw pointers.

(*) thyra/*/test_linear_op_with_solve.cpp,
thyra/*/test_composite_linear_ops.cpp: Adding mising headers hidden from
explicit instantiation

(*) thyra/example/operator_solve/CMakeLists.txt: Removed the mixed scalar test
since it is going to be ripped out soon.


Tests run on gabriel.sandia.gov:
--------------------------------

(*) CMake serial debug build of Thyra and dependencies rebuild (all 238 testss
ran passed)

(*) CMake mpi release build of Thyra and dependencies rebuild (all 204 tests
ran passed)

(*) Autotools rebuld of all libraries and tests for thyra, meros, and Sundance
(link failure in Sundance, see below)


Build failure:
--------------

Here is the build failure:
/home/rabartl/PROJECTS/Trilinos.base/BUILDS/GCC-3.4.6/MPI_OPT/packages/nox/src/libnox.a(libnox_a-NOX_Solver_Factory.o)(.text+0x286): In function `NOX::Solver::Factory::buildSolver(Teuchos::\
RCP<NOX::Abstract::Group> const&, Teuchos::RCP<NOX::StatusTest::Generic> const&, Teuchos::RCP<Teuchos::ParameterList> const&)':
: undefined reference to `NOX::Solver::TrustRegionBased::TrustRegionBased(Teuchos::RCP<NOX::Abstract::Group> const&, Teuchos::RCP<NOX::StatusTest::Generic> const&, Teuchos::RCP<Teuchos::Par\
ameterList> const&)'
collect2: ld returned 1 exit status
make: *** [RadiationDiffusion1D.exe] Error 1
make: *** Waiting for unfinished jobs....
/home/rabartl/PROJECTS/Trilinos.base/BUILDS/GCC-3.4.6/MPI_OPT/packages/nox/src/libnox.a(libnox_a-NOX_Solver_Factory.o)(.text+0x286): In function `NOX::Solver::Factory::buildSolver(Teuchos::\
RCP<NOX::Abstract::Group> const&, Teuchos::RCP<NOX::StatusTest::Generic> const&, Teuchos::RCP<Teuchos::ParameterList> const&)':
: undefined reference to `NOX::Solver::TrustRegionBased::TrustRegionBased(Teuchos::RCP<NOX::Abstract::Group> const&, Teuchos::RCP<NOX::StatusTest::Generic> const&, Teuchos::RCP<Teuchos::Par\
ameterList> const&)'
collect2: ld returned 1 exit status
make: *** [VSNS2D.exe] Error 1
/home/rabartl/PROJECTS/Trilinos.base/BUILDS/GCC-3.4.6/MPI_OPT/packages/nox/src/libnox.a(libnox_a-NOX_Solver_Factory.o)(.text+0x286): In function `NOX::Solver::Factory::buildSolver(Teuchos::\
RCP<NOX::Abstract::Group> const&, Teuchos::RCP<NOX::StatusTest::Generic> const&, Teuchos::RCP<Teuchos::ParameterList> const&)':
: undefined reference to `NOX::Solver::TrustRegionBased::TrustRegionBased(Teuchos::RCP<NOX::Abstract::Group> const&, Teuchos::RCP<NOX::StatusTest::Generic> const&, Teuchos::RCP<Teuchos::Par\
ameterList> const&)'
collect2: ld returned 1 exit status


I did not dive into this to see what the problem is but this is unrelated to
the thyra refactorings so I am going to check in without a complete test.  I
am just so tired of problems like this in the autotools system.  The only way
to know for sure is to blow everything away and build from scratch.  That can
take hours with the autools system and is hard to configure.