MueLu: fix compile error, gcc 7.2, CUDA 9 series
This commit fixes two strange compilation errors reported by Si Hammond.
The patch simply replaces the method with its definition, which is
just a single line.

Here are the errors reported:

Trilinos/packages/muelu/src/Smoothers/MueLu_IfpackSmoother.cpp:
  In member function ‘void
  MueLu::IfpackSmoother<Node>::Setup(MueLu::IfpackSmoother<Node>::Level&)’:
  Trilinos/packages/muelu/src/Smoothers/MueLu_IfpackSmoother.cpp:188:47:
  error: ‘Get<int>’ is not a member of ‘MueLu::IfpackSmoother<Node>’

Trilinos/packages/muelu/src/Smoothers/MueLu_IfpackSmoother.cpp:190:70:
error: ‘Get<Teuchos::ArrayRCP<int> >’ is not a member of
‘MueLu::IfpackSmoother<Node>’
         Teuchos::ArrayRCP<LO> TVertLineIdSmoo = Factory::Get<
         Teuchos::ArrayRCP<LO> >(currentLevel,
         "LineDetection_VertLineIds");

Build/Test Cases Summary
Enabled Packages: MueLu
Enabled all Forward Packages
0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=157,notpassed=0 (60.00 min)