Revert "WIP: Add GCC 4.9.3 to include paths for use with clang 5.0.1 (CDOFA-44)"
This reverts commit 4142e3dce0ed260139b256af5894bb5b0031d88f.

This breaks the basic confiugre of Trilinos in the compiler checks test
cmTC_6561e with a link error:

  undefined reference to symbol '_ZSt20__throw_length_errorPKc@@GLIBCXX_3.4'

Will need to work this out.

But there are missing header files if one does not add these -I paths.